### ISSUE TITLE
Weekly Log For Amir Sagiv

### ISSUE THREAD

**Issue by amirsagiv83** [TechnionYP5777/Leonidas-FTW#122]

**Comment by amirsagiv83** [comment]
Weekly log for week 1 (19.3-25.3):

- [ ]  Organizing a meeting to make sure we don't waste the first week.
- [ ]  Managing a vacations issue.
- [ ]  Making sure Plugin works and runs on different OS.
- [ ]  tried to solve the read - only problem in the SpartanizerUtils class.

**Comment by amirsagiv83** [comment]
Weekly log for week 2 (26.3-1.3):

- [ ] Started to implement our new Leonidas with Sharon and Michal.

- [ ] took part in the meeting with Yossi on building Leonidas.

- [ ] Managed Issues and vacations.

- [ ] Managing and completing my part in analyzing tippers #138, also helped with Roey's part since he is on vacation.

- [ ] Started working on GUI and created and example to the controller we want to implement. #139

- [ ] Created a wiki on JavaFX and how to use it with IntelliJ : [link](https://github.com/TechnionYP5777/IntelliJ-Spartanizer/wiki/Introduction-To-JavaFX)

**Comment by yossigil** [comment]
:100:

**Comment by amirsagiv83** [comment]
Weekly log for week 3 (2.4 - 8.4):

- [ ] Took part in a GUI team meeting

- [ ] Studied Zahi's wiki on JavaFX as asked.

- [ ] Arranged GUI missions

- [ ] Managed issues

- [ ] Developed a prototype of the toolbox controller #166 

- [ ] Created the reports project on Github and managed it.

- [ ] Closed issues #152 and #151

**Comment by amirsagiv83** [comment]
Weekly log for week 4 (18.4 - 22.4 {short week due to Passover}):

- [x] Took part in a team meeting on Tuesday.

- [x] completed the no printout tests issue. #163 

- [x] Spartanized the whole Project. #168 

- [x] Managed issues and cards.

- [x] Helped issue #170 by finding a way to load the project in eclipse by using a Gradle plugin.

- [x] Created the presentation for next week. #156 

- [x] worked with Michal on solving the bug discussed on issue #171

**Comment by amirsagiv83** [comment]
Weekly log for week 4 (23.4 - 29.4):

- [x] Took part in the lectures on Sunday and Monday.

- [x] Created Leonidas menu bar in IntelliJ. #175

- [x] Created toolBox controller GUI in Swing instead of JAVAFX. #174  

- [x] Managed issues and cards.

- [x] Created an ABOUT window for our plugin. #181 

- [x] Continued developing the toolbox controller GUI. #166

**Comment by amirsagiv83** [comment]
Weekly log for week 5 (30.4 - 6.5):

- [x] Created 'name' methods to all tippers. #176

- [x] Developed the engine for the toolbox controller and made it work properly. #166   

- [x] Managed issues and cards.

- [x] Added functionalities for the Toolbox class. 

- [x] Wrote tests for GenericPsiStatement. #185 

- [x] Wrote tests for ToolBox. #191

**Comment by amirsagiv83** [comment]
Weekly log for week 6 (7.5 - 13.5):

On Vacation.

**Comment by amirsagiv83** [comment]
Weekly log for week 7 (14.5 - 20.5):

- [x] Worked on the new Toolbox Controller. #222 

- [x] Implemented a generic components JTable. #224 

- [x] Managed issues and cards.

- [x] Added functionalities for the Toolbox class. 

- [x] Fixed a bug in the menu bar. #228
